#!/bin/sh

alias \
  e="clear" \
  r="lf" \
  lz="lazygit" \

fd ()
{
  cd $(du -a ~/ | awk '{print $2}' | fzf)
}

fe ()
{
  nvim $(du -a ~/ | awk '{print $2}' | fzf --preview 'bat --style=numbers --color=always --line-range :500 {}')
}

n ()
{
  neofetch | lolcat
}

# where proxy
proxy () {
  export http_proxy="http://localhost:7890"
  export https_proxy="http://localhost:7890"
  echo "HTTP(s) Proxy on"
}

# where noproxy
noproxy () {
  unset http_proxy
  unset https_proxy
  echo "HTTP(s) Proxy off"
}
