#!/bin/sh

alias \
  e="clear" \
  r="lf" \
  lz="lazygit" \

fd ()
{
  cd $(find ~/ -type d | fzf --reverse --height 50%)
}

fe ()
{
  nvim $(find ~/ -type f | fzf --reverse --height 50% --preview 'bat --style=numbers --color=always --line-range :500 {}')
}

n ()
{
  neofetch | lolcat
}

# where proxy
proxy () {
  export http_proxy="http://localhost:7890"
  export https_proxy="http://localhost:7890"
  echo "HTTP(s) Proxy on"
}

# where noproxy
noproxy () {
  unset http_proxy
  unset https_proxy
  echo "HTTP(s) Proxy off"
}
